apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: japavel-ingress
  namespace: japavel
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: api.japavel.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: japavel-backend
            port:
              number: 80
  - host: app.japavel.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: japavel-frontend
            port:
              number: 80
